package follow

import (
	"encoding/json"
	"regexp"
	"strings"
	"testing"
	"unicode"

	tea "github.com/charmbracelet/bubbletea"
	"github.com/charmbracelet/lipgloss"
	"github.com/charmbracelet/x/ansi"
	"github.com/muesli/termenv"

	"github.com/gualask/linqode/internal/logs"
	"github.com/gualask/linqode/internal/operations"
	"github.com/gualask/linqode/internal/tui/theme"
)

func TestLogRenderingTreatsTerminalControlsAsData(t *testing.T) {
	for name, control := range map[string]string{
		"clipboard": "\x1b]52;c;Y2xpcGJvYXJk\x07",
		"erase":     "\x1b[2J",
		"DCS":       "\x1bPpayload\x1b\\",
		"C1":        "\u009b2J",
		"controls":  "\b\a\r\n\t\x7f",
	} {
		t.Run(name, func(t *testing.T) {
			raw := "before" + control + "after"
			view := renderLogLine(logs.ParseLine(raw), false, "after", 200)
			assertSafeTerminalOutput(t, view, false)
			if text := ansi.Strip(view); !strings.Contains(text, "before") || !strings.Contains(text, "after") {
				t.Fatalf("lost surrounding text: %q", text)
			}
			data, err := json.Marshal(map[string]string{
				"msg": raw, "level": control + "info", "timestamp": control + "12:00",
				"field" + control: control + "value",
			})
			if err != nil {
				t.Fatal(err)
			}
			line := logs.ParseLine(string(data))
			view = renderLogLine(line, true, "after", 200)
			assertSafeTerminalOutput(t, view, false)
			if !strings.Contains(ansi.Strip(view), "after") {
				t.Fatalf("lost structured message: %q", view)
			}
			if message, _ := line.Record.Message(); message != raw {
				t.Fatal("rendering changed the underlying record")
			}
		})
	}
}

func TestLogControlsCannotEscapeThroughStatsOrStderrFooter(t *testing.T) {
	const control = "\x1b]52;c;Y2xpcGJvYXJk\x07"
	data, err := json.Marshal(map[string]string{"msg": "message", "level": control + "info", "source": control + "worker"})
	if err != nil {
		t.Fatal(err)
	}
	m := newTestModel(
		operations.Event{Kind: operations.EventLog, Text: string(data)},
		operations.Event{Kind: operations.EventStderr, Text: control + "failure"},
		operations.Event{Kind: operations.EventExit, ExitCode: 1},
	)
	m.showStats = true
	m.topField = "source"
	// Tall enough for the panel to reach its top values: it is cut to the
	// log's height, and the value under test is the last thing in it.
	m.SetSize(80, 24)
	view := m.View()
	assertSafeTerminalOutput(t, view, true)
	for _, want := range []string{"worker", "failure", "exit 1"} {
		if !strings.Contains(ansi.Strip(view), want) {
			t.Fatalf("%q missing from view: %q", want, view)
		}
	}
}

func TestStderrIsVisibleAndSearchableWhileRunning(t *testing.T) {
	m := newTestModel(
		operations.Event{Kind: operations.EventStderr, Text: "Traceback:"},
		operations.Event{Kind: operations.EventStdout, Text: "progress"},
		operations.Event{Kind: operations.EventStderr, Text: "connection failed"},
	)
	if view := m.View(); !strings.Contains(view, "Traceback:\nprogress\nconnection failed") {
		t.Fatalf("interleaved output missing while the command is running:\n%s", view)
	}
	m.Update(key("/"))
	m.Update(key("Traceback"))
	m.Update(tea.KeyMsg{Type: tea.KeyEnter})
	if m.matchLine != 0 {
		t.Fatalf("stderr could not be found in scrollback: match = %d", m.matchLine)
	}
}

func assertSafeTerminalOutput(t *testing.T, text string, multiline bool) {
	t.Helper()
	// Only styles generated by the view may introduce escape sequences.
	text = regexp.MustCompile(`\x1b\[[0-9;]*m`).ReplaceAllString(text, "")
	for _, r := range text {
		if unicode.IsControl(r) && !(multiline && r == '\n') {
			t.Fatalf("terminal control U+%04X survived rendering: %q", r, text)
		}
	}
}

// A search is matched against the whole record, so a hit is marked wherever
// the drawn line shows it — in a field or the timestamp, not only in the
// message.
func TestSearchHighlightsMatchesAnywhereInStructuredLine(t *testing.T) {
	lipgloss.SetColorProfile(termenv.TrueColor)
	defer lipgloss.SetColorProfile(termenv.Ascii)

	line := `{"ts":"12:00:01","level":"info","msg":"started","user":"alice"}`
	m := newTestModel(lineEvents(line, line, line)...)
	if !m.structuredRendering() {
		t.Fatal("expected structured rendering")
	}
	for query, hit := range map[string]string{
		"ALICE": "alice", // in a field, case-insensitive
		"12:00": "12:00", // in the timestamp
	} {
		m.Update(key("/"))
		typeText(m, query)
		m.Update(tea.KeyMsg{Type: tea.KeyEnter})
		body := m.logBody(120)
		if !strings.Contains(body, theme.Match.Render(hit)) {
			t.Errorf("query %q: %q not highlighted in %q", query, hit, body)
		}
		if got := ansi.Strip(body); !strings.Contains(got, "12:00:01 info  started user=alice") {
			t.Errorf("query %q changed the text: %q", query, got)
		}
	}
}
