package follow

import (
	"encoding/json"
	"regexp"
	"strings"
	"testing"
	"unicode"

	tea "github.com/charmbracelet/bubbletea"
	"github.com/charmbracelet/lipgloss"
	"github.com/charmbracelet/x/ansi"
	"github.com/muesli/termenv"

	"github.com/gualask/linqode/internal/logs"
	"github.com/gualask/linqode/internal/operations"
	"github.com/gualask/linqode/internal/tui/theme"
)

func TestLogRenderingTreatsTerminalControlsAsData(t *testing.T) {
	for name, control := range map[string]string{
		"clipboard": "\x1b]52;c;Y2xpcGJvYXJk\x07",
		"erase":     "\x1b[2J",
		"DCS":       "\x1bPpayload\x1b\\",
		"C1":        "\u009b2J",
		"controls":  "\b\a\r\n\t\x7f",
	} {
		t.Run(name, func(t *testing.T) {
			raw := "before" + control + "after"
			view := renderLogLine(logs.ParseLine(raw), false, lineMarks{query: "after"}, 200)
			assertSafeTerminalOutput(t, view, false)
			if text := ansi.Strip(view); !strings.Contains(text, "before") || !strings.Contains(text, "after") {
				t.Fatalf("lost surrounding text: %q", text)
			}
			data, err := json.Marshal(map[string]string{
				"msg": raw, "level": control + "info", "timestamp": control + "12:00",
				"field" + control: control + "value",
			})
			if err != nil {
				t.Fatal(err)
			}
			line := logs.ParseLine(string(data))
			view = renderLogLine(line, true, lineMarks{query: "after"}, 200)
			assertSafeTerminalOutput(t, view, false)
			if !strings.Contains(ansi.Strip(view), "after") {
				t.Fatalf("lost structured message: %q", view)
			}
			if message, _ := line.Record.Message(); message != raw {
				t.Fatal("rendering changed the underlying record")
			}
		})
	}
}

func TestLogControlsCannotEscapeThroughStatsOrStderrFooter(t *testing.T) {
	const control = "\x1b]52;c;Y2xpcGJvYXJk\x07"
	data, err := json.Marshal(map[string]string{"msg": "message", "level": control + "info", "source": control + "worker"})
	if err != nil {
		t.Fatal(err)
	}
	m := newTestModel(
		operations.Event{Kind: operations.EventLog, Text: string(data)},
		operations.Event{Kind: operations.EventStderr, Text: control + "failure"},
		operations.Event{Kind: operations.EventExit, ExitCode: 1},
	)
	m.showStats = true
	m.topField = "source"
	// Tall enough for the panel to reach its top values: it is cut to the
	// log's height, and the value under test is the last thing in it.
	m.SetSize(80, 24)
	view := m.View()
	assertSafeTerminalOutput(t, view, true)
	for _, want := range []string{"worker", "failure", "exit 1"} {
		if !strings.Contains(ansi.Strip(view), want) {
			t.Fatalf("%q missing from view: %q", want, view)
		}
	}
}

func TestStderrIsVisibleAndSearchableWhileRunning(t *testing.T) {
	m := newTestModel(
		operations.Event{Kind: operations.EventStderr, Text: "Traceback:"},
		operations.Event{Kind: operations.EventStdout, Text: "progress"},
		operations.Event{Kind: operations.EventStderr, Text: "connection failed"},
	)
	if view := m.View(); !strings.Contains(view, "Traceback:\nprogress\nconnection failed") {
		t.Fatalf("interleaved output missing while the command is running:\n%s", view)
	}
	m.Update(key("/"))
	m.Update(key("Traceback"))
	m.Update(tea.KeyMsg{Type: tea.KeyEnter})
	if m.matchLine != 0 {
		t.Fatalf("stderr could not be found in scrollback: match = %d", m.matchLine)
	}
}

func assertSafeTerminalOutput(t *testing.T, text string, multiline bool) {
	t.Helper()
	// Only styles generated by the view may introduce escape sequences.
	text = regexp.MustCompile(`\x1b\[[0-9;]*m`).ReplaceAllString(text, "")
	for _, r := range text {
		if unicode.IsControl(r) && !(multiline && r == '\n') {
			t.Fatalf("terminal control U+%04X survived rendering: %q", r, text)
		}
	}
}

// A search is matched against the whole record, so a hit is marked wherever
// the drawn line shows it — in a field or the timestamp, not only in the
// message.
func TestSearchHighlightsMatchesAnywhereInStructuredLine(t *testing.T) {
	lipgloss.SetColorProfile(termenv.TrueColor)
	defer lipgloss.SetColorProfile(termenv.Ascii)

	line := `{"ts":"12:00:01","level":"info","msg":"started","user":"alice"}`
	m := newTestModel(lineEvents(line, line, line)...)
	if !m.structuredRendering() {
		t.Fatal("expected structured rendering")
	}
	for query, hit := range map[string]string{
		"ALICE": "alice", // in a field, case-insensitive
		"12:00": "12:00", // in the timestamp
	} {
		m.Update(key("/"))
		typeText(m, query)
		m.Update(tea.KeyMsg{Type: tea.KeyEnter})
		body := m.logBody(120)
		if !strings.Contains(body, theme.Match.Render(hit)) {
			t.Errorf("query %q: %q not highlighted in %q", query, hit, body)
		}
		if got := ansi.Strip(body); !strings.Contains(got, "12:00:01 info  started user=alice") {
			t.Errorf("query %q changed the text: %q", query, got)
		}
	}
}

// The hit n/N stopped on is drawn apart from the others, and moves with them.
func TestCurrentMatchIsSetApart(t *testing.T) {
	lipgloss.SetColorProfile(termenv.TrueColor)
	defer lipgloss.SetColorProfile(termenv.Ascii)

	m := newTestModel(lineEvents("alpha one alpha", "noise", "alpha two")...)
	m.Update(key("/"))
	typeText(m, "alpha")
	m.Update(tea.KeyMsg{Type: tea.KeyEnter})

	current, other := theme.MatchCurrent.Render("alpha"), theme.Match.Render("alpha")
	// Following, the search lands on the newest match. It leaves the cursor
	// on the match too; the hits keep their colours on the cursor's bar.
	lines := strings.Split(m.logBody(80), "\n")
	if !strings.HasPrefix(lines[2], current) {
		t.Errorf("current line = %q, want its hit current", lines[2])
	}
	if strings.Contains(lines[0], current) || !strings.Contains(lines[0], other) {
		t.Errorf("other line = %q, want only plain matches", lines[0])
	}

	m.Update(key("N"))
	lines = strings.Split(m.logBody(80), "\n")
	if !strings.HasPrefix(lines[0], current) || !strings.Contains(lines[0], other) ||
		strings.Contains(lines[2], current) {
		t.Errorf("after N the current match did not move, or took both hits:\n%s",
			strings.Join(lines, "\n"))
	}
}

// A line is cut by the cells it takes, not by its characters: wide ones take
// two, and cut by count the line would be twice its width — beside the stats
// panel, a second row that pushes the footer off the screen.
func TestWideCharactersAreCutByWidth(t *testing.T) {
	wide := strings.Repeat("日本語", 40)
	for _, structured := range []bool{false, true} {
		line := logs.LogLine{Raw: wide}
		if structured {
			line = logs.LogLine{Raw: `{"msg":"` + wide + `"}`, Record: logs.ParseRecord(`{"msg":"` + wide + `"}`)}
		}
		got := renderLogLine(line, structured, lineMarks{}, 40)
		if width := ansi.StringWidth(got); width > 40 {
			t.Errorf("structured=%v: a line for 40 cells is %d wide: %q", structured, width, got)
		}
	}
	var many []string
	for range 20 {
		many = append(many, wide)
	}
	m := newTestModel(lineEvents(many...)...)
	m.SetSize(80, 10)
	m.Update(key("a"))
	rows := strings.Split(m.View(), "\n")
	if len(rows) > 10 {
		t.Errorf("the frame is %d rows on a 10-row terminal:\n%s", len(rows), m.View())
	}
	for _, row := range rows {
		if width := ansi.StringWidth(row); width > 80 {
			t.Errorf("a row is %d wide on 80 columns: %q", width, row)
		}
	}
}

// A footer never wraps: the filter prompt, opened with a whole filter in it,
// keeps the end of what is typed and drops the hint first.
func TestTheFilterPromptFitsTheWidth(t *testing.T) {
	m := newTestModel(jsonlEvents(3, "error")...)
	m.SetSize(40, 10)
	filter, err := logs.ParseFilter(`level=error route=/api/login/with/a/long/path`)
	if err != nil {
		t.Fatal(err)
	}
	m.store.SetFilter(filter)
	m.Update(key("f"))
	footer := m.footer()
	if width := ansi.StringWidth(footer); width > 40 {
		t.Errorf("the prompt is %d wide on 40 columns: %q", width, footer)
	}
	if !strings.Contains(footer, "long/path▏") {
		t.Errorf("the end of the filter, where the typing is, was cut: %q", ansi.Strip(footer))
	}
	m.Update(tea.KeyMsg{Type: tea.KeyEsc})
	m.notice = strings.Repeat("a very long notice ", 10)
	if width := ansi.StringWidth(m.footer()); width > 40 {
		t.Errorf("the notice is %d wide on 40 columns", width)
	}
}

// The header is the title the operator typed after `!`, and was the one line
// of the view nothing cut: a long one wrapped, and the frame was a row taller
// than the screen.
func TestTheHeaderIsCutToTheWidth(t *testing.T) {
	title := "$ " + strings.Repeat("echo something long; ", 8)
	for _, open := range []bool{false, true} {
		feed, _ := feedOf(lineEvents("first line")...)
		m := New("deploy@prod", title, feed)
		m.SetSize(60, 12)
		m.drain()
		if open {
			m.Update(tea.KeyMsg{Type: tea.KeyEnter})
		}
		view := m.View()
		header := strings.Split(view, "\n")[0]
		if width := lipgloss.Width(header); width > 60 {
			t.Errorf("the header is %d cells at 60 (line open: %v): %q", width, open, header)
		}
		if lines := strings.Count(view, "\n") + 1; lines > 12 {
			t.Errorf("the frame is %d rows on a 12-row screen (line open: %v)", lines, open)
		}
	}
}
